# Generated by Django 5.0.2 on 2024-03-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(blank=True, default='https://convida.pt/images/POIs/Restaurantes_01.jpg', max_length=500),
        ),
    ]
